const PRODUCTS_EXCEL_PATH = "\\\\10.0.0.20\\Compras\\1.COMPRAS\\SAULO\\ALFADIME\\PRODUTOS\\PRODUTOS.xlsx";

const PRODUCTS_EXCEL_FILE_NAME =
    "PRODUTOS.xlsx";

const PRODUCTS_EXCEL_SHEET_NAME = null;

const PRODUCTS_EXCEL_POLLING_INTERVAL = 5000;

const PRODUCTS_EXCEL_STABILITY_CHECK_DELAY = 1500;

module.exports = {
    PRODUCTS_EXCEL_PATH,
    PRODUCTS_EXCEL_FILE_NAME,
    PRODUCTS_EXCEL_SHEET_NAME,
    PRODUCTS_EXCEL_POLLING_INTERVAL,
    PRODUCTS_EXCEL_STABILITY_CHECK_DELAY
};
