const PURCHASES_CURVE_EXCEL_PATH =
    "\\\\10.0.0.20\\Compras\\1.COMPRAS\\SAULO\\ALFADIME\\CURVA COMPRAS\\CURVA COMPRAS.xlsx";

const CURVE_EXCEL_FILE_NAME = "CURVA COMPRAS.xlsx";

const CURVE_EXCEL_SHEET_NAME = null;

const CURVE_EXCEL_POLLING_INTERVAL = 5000;

const CURVE_EXCEL_STABILITY_CHECK_DELAY = 1500;

module.exports = {
    PURCHASES_CURVE_EXCEL_PATH,
    CURVE_EXCEL_FILE_NAME,
    CURVE_EXCEL_SHEET_NAME,
    CURVE_EXCEL_POLLING_INTERVAL,
    CURVE_EXCEL_STABILITY_CHECK_DELAY
};
